// DO NOT EDIT THIS FILE

import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'bootstrap/dist/css/bootstrap.min.css'
import store from './store'
import App from './App.vue'
Vue.config.productionTip = false
Vue.use(Vuetify)
new Vue({
	render: (h) => h(App),
	vuetify: new Vuetify({}),
	store
}).$mount('#vue-gets-rendered-here')
